CXXFLAGS=-O0 -g

all:
	g++ -o bi-stat-score bi-stat-score.cpp 
	g++ -o bi-stat-build-index bi-stat-build-index.cpp
	g++ -o one-to-ne-lang-model one-to-ne-lang-model.cpp

clear:
	rm -rf bi-stat-score bi-stat-build-index one-to-ne-lang-model

